### ISSUE TITLE
[2.18.2] Crashes on High Sierra

### ISSUE THREAD

**Issue by gingerbeardman** [jfiguinha/Regards#1]
2.18.2 crashes on High Sierra

Will not launch.

- 2.18.2 FAILS
- 2.18.1 WORKS

**Comment by jfiguinha** [comment]
Thanks for your return
The 2.18.2 was compiled on Mojave. 
I have published a new version compiled on High Sierra

**Comment by gingerbeardman** [comment]
Thanks!
