### ISSUE TITLE
Won't run on Pop!_OS 20.10 missing libqpdf.so.26

### ISSUE THREAD

**Issue by johnblommers** [jfiguinha/Regards#2]
Regards installs fine from the `.deb` file. At runtime it won't launch because it wants specific but older non-installed versions of specific libraries:

- `libqpdf.so.26`
- `libHalf.so.24`
- `libIlmImf-2_3.so.24`

Creating symbolic links from the more current versions of these libraries to the above file names fails because Regards is looking for specific versions of the libraries.

By all appearances the `.deb` installation file does not specify these dependencies. 

Rather than shipping a `.deb` package please consider packaging the dependencies inside an AppImage bundle and shipping that.

**Comment by jfiguinha** [comment]
Thanks for your return.
I will test it and correct the problem.

**Comment by jfiguinha** [comment]
Regards Viewer 2 works on PopOs 20.10. I corrected all depedencies problem.
Best Regards
