### ISSUE TITLE
Can't install on Archlinux missing dependency package libgnutls28

### ISSUE THREAD

**Issue by ryanlycch** [jfiguinha/Regards#3]
warning: cannot resolve "libgnutls28", a dependency of "regardsviewer-bin"

and the aur package "gnutls28" compile error: 
aes-padlock.c:96:28: error: 'struct aes_ctx' has no member named 'keys'
   96 |   memcpy(pce->ks.rd_key, nc.keys, sizeof(nc.keys));
      |                            ^
aes-padlock.c:96:44: error: 'struct aes_ctx' has no member named 'keys'
   96 |   memcpy(pce->ks.rd_key, nc.keys, sizeof(nc.keys));
      |                                            ^
aes-padlock.c:98:22: error: 'struct aes_ctx' has no member named 'rounds'
   98 |   pce->ks.rounds = nc.rounds;
      |                      ^
make[5]: *** [Makefile:1578: aes-padlock.lo] Error 1

**Comment by jfiguinha** [comment]
Hi, thanks for your report. Can you tell me the version of archlinux and the gui use in your case ? The arch package in release is made for manjaro latest distribution. Best regards

**Comment by ryanlycch** [comment]
archlinux version:  2021.1
LSB_VERSION=1.4
DISTRIB_ID=Arch
DISTRIB_RELEASE=rolling
DISTRIB_DESCRIPTION="Arch Linux"

kernel version
Linux  5.10.4-zen2-1-zen #1 ZEN SMP PREEMPT Fri, 01 Jan 2021 05:29:58 +0000 x86_64 GNU/Linux

gui env
gnome 3.38

**Comment by jfiguinha** [comment]
Hi,
Missing package has been corrected. I updated the arch package in Release folder.
