### ISSUE TITLE
libm.so.6: version 'GLIBC_2.29' not found

### ISSUE THREAD

**Issue by herbert256** [jfiguinha/Regards#4]
Environment: ChromeOS / Crostini / Debian 10.7

I installed RegardsViewer with below commands.

cd /tmp
wget https://github.com/jfiguinha/Regards/releases/download/v2.63.7/RegardsViewer_2.63.7_amd64_20.04.deb
apt -y install ./Regards*.deb
rm Regards*.deb

The install did work, apt did add 161 other packages.

When I start RegardsViewer, below errors occur.

./RegardsViewer: /lib/x86_64-linux-gnu/libm.so.6: version 'GLIBC_2.29' not found (required by ./RegardsViewer)
./RegardsViewer: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version 'GLIBCXX_3.4.26' not found (required by ./RegardsViewer)
./RegardsViewer: /lib/x86_64-linux-gnu/libm.so.6: version 'GLIBC_2.29' not found (required by ./liblibde265.so)
./RegardsViewer: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version 'GLIBCXX_3.4.26' not found (required by ./liblibde265.so)
./RegardsViewer: /lib/x86_64-linux-gnu/libm.so.6: version 'GLIBC_2.29' not found (required by ./libexiv2.so.27)
./RegardsViewer: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version 'GLIBCXX_3.4.26' not found (required by ./libexiv2.so.27)
./RegardsViewer: /lib/x86_64-linux-gnu/libm.so.6: version 'GLIBC_2.29' not found (required by ./libjasper.so.4)
./RegardsViewer: /lib/x86_64-linux-gnu/libm.so.6: version 'GLIBC_2.29' not found (required by ./libraw_r.so.20)
./RegardsViewer: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version 'GLIBCXX_3.4.26' not found (required by ./libqpdf.so.28)
./RegardsViewer: /lib/x86_64-linux-gnu/libm.so.6: version 'GLIBC_2.29' not found (required by ./libtesseract.so.4.1.1)
./RegardsViewer: /lib/x86_64-linux-gnu/libm.so.6: version 'GLIBC_2.29' not found (required by ./libIlmImf-2_5.so.25)
./RegardsViewer: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version 'GLIBCXX_3.4.26' not found (required by ./libIlmImf-2_5.so.25)
./RegardsViewer: /lib/x86_64-linux-gnu/libm.so.6: version 'GLIBC_2.29' not found (required by ./libopencv_core.so.4.3)
./RegardsViewer: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version 'GLIBCXX_3.4.26' not found (required by ./libopencv_core.so.4.3)
./RegardsViewer: /lib/x86_64-linux-gnu/libm.so.6: version 'GLIBC_2.29' not found (required by ./libopencv_dnn.so.4.3)
./RegardsViewer: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version 'GLIBCXX_3.4.26' not found (required by ./libopencv_dnn.so.4.3)
./RegardsViewer: /lib/x86_64-linux-gnu/libm.so.6: version 'GLIBC_2.29' not found (required by ./libopencv_imgproc.so.4.3)
./RegardsViewer: /lib/x86_64-linux-gnu/libm.so.6: version 'GLIBC_2.29' not found (required by ./libopencv_imgcodecs.so.4.3)
./RegardsViewer: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version 'GLIBCXX_3.4.26' not found (required by ./libopencv_imgcodecs.so.4.3)
./RegardsViewer: /lib/x86_64-linux-gnu/libm.so.6: version 'GLIBC_2.29' not found (required by ./libopencv_face.so.4.3)
./RegardsViewer: /lib/x86_64-linux-gnu/libm.so.6: version 'GLIBC_2.29' not found (required by ./libopencv_objdetect.so.4.3)
./RegardsViewer: /lib/x86_64-linux-gnu/libm.so.6: version 'GLIBC_2.29' not found (required by ./libx265.so.179)
./RegardsViewer: /lib/x86_64-linux-gnu/libm.so.6: version 'GLIBC_2.29' not found (required by ./libpoppler.so.104)
./RegardsViewer: /lib/x86_64-linux-gnu/libm.so.6: version 'GLIBC_2.29' not found (required by ./libopencv_calib3d.so.4.3)
./RegardsViewer: /lib/x86_64-linux-gnu/libm.so.6: version 'GLIBC_2.29' not found (required by ./libopencv_features2d.so.4.3)
./RegardsViewer: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version 'GLIBCXX_3.4.26' not found (required by ./libopencv_flann.so.4.3)

I found below files on my system

/lib/x86_64-linux-gnu/libm.so.6
/lib/x86_64-linux-gnu/libm-2.28.so

/usr/lib/x86_64-linux-gnu/libstdc++.so.6
/usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.25

**Comment by jfiguinha** [comment]
Hi,
For the moment, I don't support chromebook. I don't have one to test it but you can try to compile it. You can follow the compilation procedure in the wiki for linux system.
Best regards

**Comment by jfiguinha** [comment]
Chrome OS not supported
