### ISSUE TITLE
missing library function on Linux Mint installation

### ISSUE THREAD

**Issue by githubber94** [jfiguinha/Regards#6]
I just installed the latest version under Linux Mint 20 and got the following error when I attempted to run the software:

./RegardsViewer: symbol lookup error: ./RegardsViewer: undefined symbol: eglCreatePlatformWindowSurface

Update:  I've been informed by Figuinha (see below) that this error is from my (Nvidia) graphics card, and is likely the result of the drivers needing an update, which I will now investigate.

**Comment by jfiguinha** [comment]
Hi,
Can you send me your PC configuration ?
It's not a missing library but an error from your graphic card. Have you updated your nvidia driver before you try this new version ?
Best Regards

**Comment by jfiguinha** [comment]
Old issue
